function para1 = a_cal_source(para)
    th = para.th;
    Ath = para.FSInfo.ThAth(:,2);
    px = para.FSInfo.XY(:,1);
    py = para.FSInfo.XY(:,2);
    vx = para.FSInfo.VFxy(:,1);
    vy = para.FSInfo.VFxy(:,2);
    N = trapz(th,Ath);
    p2barx = trapz(th,Ath.*px.^2);
    p2bary = trapz(th,Ath.*py.^2);
    para.src.fthorder = "Theta_Y0_Yx_Yy_jx_jy_Ey";
    para.src.fth(:,1) = th;
    para.src.fth(:,2) = ones(size(th))./sqrt(N);
    para.src.fth(:,3) = 1/sqrt(p2barx)*px;
    para.src.fth(:,4) = 1/sqrt(p2bary)*py;
    para.src.fth(:,5) = vx;
    para.src.fth(:,6) = vy;
    para = a_cal_modes(para);
    para1 = para;
end